### ISSUE TITLE
demo checklist

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/designengine.ai#728]
**Free Inspect**

- [ ] Click on URL from Slack
- [ ] Open Free Inspect to a project with 3 mobile screens
- [ ] Rollover to inspect across several objects watching tab change & linting/debugging 
- [ ] Click on a object to highlight
- [ ] Click through tabs to see each lint/debug 
- [ ] Click back on HTML tab
- [ ] Copy HTML
- [ ] Gist HTML
- [ ] Go back to Slack and click on another URL
- [ ] Open Free Inspect to a project with 5 mobile screens
- [ ] Rollover to inspect across several objects watching tab change & linting/debugging 
- [ ] Scroll through specs, copying a few rows & the entire specs blog

**Editor**

- [ ] Click Edit Button
- [ ] Open Editor
- [ ] Rollover to inspect across several objects watching tab change & linting/debugging 
- [ ] Rolloff to see entire HTML
- [ ] Click through tabs to see each lint/debug 
- [ ] Click back to the css tab and change the BG color
- [ ] Hit Run but don't have it do anything I will walk through it
