### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/designengine.ai#760]
**Tasks**
- [ ] Save button should overwrite local json & Onload we need to save local json Gist if user is logged in & display url
- [x] See if you can smooth out page drawing, when the view loads you can see each section load oddly instead of all at once (left side and editor and live view)
- [x] The editor is moving around on rollover, expanding the right side view oddly (bug)
- [x] Add Linter back in
- [x] Not all elements you select are being rendered correctly, for example the check icons are selectable but not display (maybe needs re-processing)?

**Onload**
![Editor Onload](https://user-images.githubusercontent.com/1239243/58301532-a26d8480-7d9b-11e9-98e2-b50e4d7cfa2c.png)

**Rollover**
![Editor Rollover](https://user-images.githubusercontent.com/1239243/58301536-a4cfde80-7d9b-11e9-9c05-a4a02d1b3f1f.png)

**Click**
![Editor Click](https://user-images.githubusercontent.com/1239243/58301539-a7cacf00-7d9b-11e9-9459-a0cd38a4f0ae.png)
