### ISSUE TITLE
Free Specs

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/designengine.ai#761]
**Tasks**

- [x] Match onload state to display gray version of specs
- [x] Missing header background under Specs (look over all right side styling)
- [x] Adjust spec ordering to match comps
- [x] Make the on-click grid line 2px 
- [x] Add the ability to right click on any design object and see a drop down (see comps)
- [x] Add the ability to Tab (key command) between Specs, Styles, and Editor (loads same design file you are viewing in the next section)
- [x] Make sure the upload screen says "Upload a design file for Free Specs"
- [x] Make sure the Try Demo file works
- [x] Match **exactly** to comps (below)

**Onload**
![Free Specs Onload](https://user-images.githubusercontent.com/1239243/58186903-a0f06f00-7c6a-11e9-8368-206237599c8f.png)

**Rollover**
![Free Specs Rollover](https://user-images.githubusercontent.com/1239243/58186918-a3eb5f80-7c6a-11e9-94e1-695823b2e347.png)

**Click**
![Free Specs Click](https://user-images.githubusercontent.com/1239243/58186921-a5b52300-7c6a-11e9-8eff-768b0848b5fc.png)

**Right Click**
![Free Specs Right Click](https://user-images.githubusercontent.com/1239243/58187557-d5185f80-7c6b-11e9-9574-ee98e7bc1e15.png)
